/* GENERATED by build-manifest.mjs — do not edit by hand.
   Snapshots live in projects/. Everything else comes from the GitHub API, so a
   project with no snapshot still appears rather than silently vanishing.
   Regenerate: node build-manifest.mjs */

window.DESIGN_LIBRARY = {
  "title": "Pragmatic Design Library",
  "subtitle": "versioned UI prototypes",
  "initial": "P",
  "repoUrl": "https://github.com/pragmaticlabsdevelopment/design-library",
  "projects": [
    {
      "slug": "get-pragmatic",
      "name": "Get Pragmatic",
      "description": "Pragmatic Labs marketing site",
      "versions": [
        {
          "id": "v2",
          "label": "Redesign",
          "date": "2026-09-13",
          "status": "draft",
          "notes": "Starting point for the next iteration.",
          "path": "projects/get-pragmatic/v2/index.html"
        },
        {
          "id": "v1",
          "label": "Current live site",
          "date": "2026-09-13",
          "status": "current",
          "notes": "As deployed.",
          "path": "projects/get-pragmatic/v1/index.html"
        }
      ],
      "repoUrl": "https://github.com/pragmatic-labs-development/pragmatic-website",
      "liveUrl": "https://pragmatic-labs-development.github.io/pragmatic-website/",
      "visibility": "PUBLIC",
      "archived": false,
      "language": "HTML",
      "updated": "2026-08-22"
    },
    {
      "slug": "envisor",
      "name": "Envisor",
      "description": "Launchpad app + ten marketing concepts",
      "versions": [
        {
          "id": "launchpad",
          "label": "Launchpad (app)",
          "date": "2026-08-24",
          "status": "current",
          "notes": "The product itself, not the marketing site.",
          "path": "projects/envisor-demo/launchpad/index.html"
        },
        {
          "id": "v10",
          "label": "Marketing v10",
          "date": "2026-08-24",
          "status": "current",
          "notes": "",
          "path": "projects/envisor-demo/v10/index.html"
        },
        {
          "id": "v9",
          "label": "Marketing v9",
          "date": "2026-08-24",
          "status": "superseded",
          "notes": "",
          "path": "projects/envisor-demo/v9/index.html"
        },
        {
          "id": "v8",
          "label": "Marketing v8",
          "date": "2026-08-24",
          "status": "superseded",
          "notes": "",
          "path": "projects/envisor-demo/v8/index.html"
        },
        {
          "id": "v7",
          "label": "Marketing v7",
          "date": "2026-08-24",
          "status": "superseded",
          "notes": "",
          "path": "projects/envisor-demo/v7/index.html"
        },
        {
          "id": "v6",
          "label": "Marketing v6",
          "date": "2026-08-24",
          "status": "superseded",
          "notes": "",
          "path": "projects/envisor-demo/v6/index.html"
        },
        {
          "id": "v5",
          "label": "Marketing v5",
          "date": "2026-08-24",
          "status": "superseded",
          "notes": "",
          "path": "projects/envisor-demo/v5/index.html"
        },
        {
          "id": "v4",
          "label": "Marketing v4",
          "date": "2026-08-24",
          "status": "superseded",
          "notes": "",
          "path": "projects/envisor-demo/v4/index.html"
        },
        {
          "id": "v3",
          "label": "Marketing v3",
          "date": "2026-08-24",
          "status": "superseded",
          "notes": "",
          "path": "projects/envisor-demo/v3/index.html"
        },
        {
          "id": "v2",
          "label": "Marketing v2",
          "date": "2026-08-24",
          "status": "superseded",
          "notes": "",
          "path": "projects/envisor-demo/v2/index.html"
        },
        {
          "id": "v1",
          "label": "Marketing v1",
          "date": "2026-08-24",
          "status": "superseded",
          "notes": "",
          "path": "projects/envisor-demo/v1/index.html"
        }
      ],
      "repoUrl": "https://github.com/pragmatic-labs-development/envisor",
      "liveUrl": null,
      "visibility": "PRIVATE",
      "archived": false,
      "language": "HTML",
      "updated": "2026-08-24"
    },
    {
      "slug": "nudgy-website",
      "name": "Nudgy — screenshot tool",
      "description": "The original Mac screenshot tool. Archived Sept 2026.",
      "versions": [
        {
          "id": "v1",
          "label": "Live site",
          "date": "2026-09-13",
          "status": "archived",
          "notes": "Frozen when Nudgy became a personal CRM.",
          "path": "projects/nudgy-website/v1/index.html"
        }
      ],
      "repoUrl": "https://github.com/pragmatic-labs-development/nudgy-legacy-desktop",
      "liveUrl": null,
      "visibility": "PRIVATE",
      "archived": true,
      "language": "TypeScript",
      "updated": "2026-09-25"
    },
    {
      "slug": "aipm",
      "name": "AIPM",
      "description": "AI product management",
      "versions": [
        {
          "id": "v1",
          "label": "Live site",
          "date": "2026-09-13",
          "status": "current",
          "notes": "",
          "path": "projects/aipm/v1/index.html"
        }
      ],
      "repoUrl": "https://github.com/pragmatic-labs-development/aipm",
      "liveUrl": "https://pragmatic-labs-development.github.io/aipm/",
      "visibility": "PUBLIC",
      "archived": false,
      "language": "Astro",
      "updated": "2026-08-22"
    },
    {
      "slug": "pickpack",
      "name": "PickPack",
      "description": "PickPack marketing site",
      "versions": [
        {
          "id": "v1",
          "label": "Live site",
          "date": "2026-09-13",
          "status": "current",
          "notes": "",
          "path": "projects/pickpack/v1/index.html"
        }
      ],
      "repoUrl": "https://github.com/pragmatic-labs-development/pickpack-marketing",
      "liveUrl": null,
      "visibility": "PRIVATE",
      "archived": false,
      "language": "TypeScript",
      "updated": "2026-05-22"
    },
    {
      "slug": "inspection-software",
      "name": "Inspection Software",
      "description": "Modern OS for inspection businesses",
      "versions": [
        {
          "id": "v1",
          "label": "Live site",
          "date": "2026-09-13",
          "status": "current",
          "notes": "",
          "path": "projects/inspection-software/v1/index.html"
        }
      ],
      "repoUrl": "https://github.com/pragmatic-labs-development/inspection-software",
      "liveUrl": null,
      "visibility": "PRIVATE",
      "archived": false,
      "language": "TypeScript",
      "updated": "2026-05-25"
    },
    {
      "slug": "chads-gpt",
      "name": "Chad's GPT",
      "description": "ChatGPT parody marketing site",
      "versions": [
        {
          "id": "v1",
          "label": "Live site",
          "date": "2026-09-13",
          "status": "current",
          "notes": "",
          "path": "projects/chads-gpt/v1/index.html"
        }
      ],
      "repoUrl": "https://github.com/pragmatic-labs-development/chads-gpt",
      "liveUrl": "https://chads-gpt.com",
      "visibility": "PUBLIC",
      "archived": false,
      "language": "TypeScript",
      "updated": "2026-04-04"
    },
    {
      "slug": "design-library",
      "name": "Design Library",
      "description": "Versioned UI prototype library — click through projects and design versions",
      "repoUrl": "https://github.com/pragmaticlabsdevelopment/design-library",
      "liveUrl": "https://pragmaticlabsdevelopment.github.io/design-library/",
      "visibility": "PUBLIC",
      "archived": false,
      "language": "HTML",
      "updated": "2026-09-27",
      "versions": []
    },
    {
      "slug": "projects-index",
      "name": "Projects Index",
      "description": "",
      "repoUrl": "https://github.com/pragmatic-labs-development/projects-index",
      "liveUrl": "https://pragmatic-labs-development.github.io/projects-index/",
      "visibility": "PUBLIC",
      "archived": false,
      "language": "HTML",
      "updated": "2026-09-27",
      "versions": []
    },
    {
      "slug": "nudgy",
      "name": "Nudgy",
      "description": "",
      "repoUrl": "https://github.com/pragmatic-labs-development/nudgy",
      "liveUrl": null,
      "visibility": "PRIVATE",
      "archived": false,
      "language": "TypeScript",
      "updated": "2026-09-25",
      "versions": [],
      "alsoUrl": "https://pragmatic-labs-development.github.io/nudgy-site/",
      "alsoLabel": "Marketing site"
    },
    {
      "slug": "pickup-soccer-bot",
      "name": "Pickup Soccer Bot",
      "description": "",
      "repoUrl": "https://github.com/pragmaticlabsdevelopment/pickup-soccer-bot",
      "liveUrl": null,
      "visibility": "PRIVATE",
      "archived": false,
      "language": "JavaScript",
      "updated": "2026-09-25",
      "versions": []
    },
    {
      "slug": "domain-bot",
      "name": "Domain Bot",
      "description": "",
      "repoUrl": "https://github.com/pragmatic-labs-development/domain-bot",
      "liveUrl": "https://pragmatic-labs-development.github.io/domain-bot/",
      "visibility": "PUBLIC",
      "archived": false,
      "language": "JavaScript",
      "updated": "2026-08-22",
      "versions": []
    },
    {
      "slug": "anaconda-ai-governance-dashboard",
      "name": "Anaconda AI Governance",
      "description": "AI Governance Dashboard - Portfolio Demo",
      "repoUrl": "https://github.com/pragmatic-labs-development/anaconda-ai-governance-dashboard",
      "liveUrl": null,
      "visibility": "PRIVATE",
      "archived": true,
      "language": "CSS",
      "updated": "2026-06-05",
      "versions": []
    },
    {
      "slug": "box-ops",
      "name": "Box Ops",
      "description": "",
      "repoUrl": "https://github.com/pragmatic-labs-development/box-ops",
      "liveUrl": "https://box-ops.vercel.app",
      "visibility": "PUBLIC",
      "archived": false,
      "language": "TypeScript",
      "updated": "2026-04-27",
      "versions": []
    },
    {
      "slug": "TeachGPT",
      "name": "TeachGPT",
      "description": "",
      "repoUrl": "https://github.com/pragmatic-labs-development/TeachGPT",
      "liveUrl": null,
      "visibility": "PRIVATE",
      "archived": false,
      "language": "TypeScript",
      "updated": "2026-03-22",
      "versions": []
    }
  ]
};
